<?php

class DbConfig {
    //Define table constant
    CONST TABLE_USER='tbl_user';
    CONST TABLE_USER_ATT_USER_ID='userId';
    CONST TABLE_USER_ATT_NAME='name';
    CONST TABLE_USER_ATT_EMAIL='email';
    CONST TABLE_USER_ATT_PASSWORD='password';
    CONST TABLE_USER_ATT_REGISTRATION_DATE='registrationDate';
    CONST TABLE_USER_ATT_LAST_LOGIN_DATE='lastLoginDate';
    CONST TABLE_USER_ATT_LAST_LOGIN_IP='lastLoginIP';
    CONST TABLE_USER_ATT_IS_ACTIVE='isActive';
    CONST TABLE_USER_ATT_IS_DELETED='isDeleted';
    
    CONST TABLE_USER_INFO='tbl_user_info';
    CONST TABLE_USER_INFO_ATT_USER_INFO_ID='userInfoId';
    CONST TABLE_USER_INFO_ATT_USER_ID='userId';
    CONST TABLE_USER_INFO_ATT_PROFILE_IMAGE='profileImage';
    CONST TABLE_USER_INFO_ATT_COVER_IMAGE='coverImage';
    
    CONST TABLE_FEED='tbl_feed';
    CONST TABLE_FEED_ATT_FEED_ID='feedId';
    CONST TABLE_FEED_ATT_USER_ID='userId';
    CONST TABLE_FEED_ATT_FEED_TEXT='feedText';
    CONST TABLE_FEED_ATT_IMAGE_NAME='imageName';
    CONST TABLE_FEED_ATT_POST_DATE='postDate';
    
    CONST TABLE_CONNECTION='tbl_connection';
    CONST TABLE_CONNECTION_ATT_='connectionId';
    CONST TABLE_CONNECTION_ATT_USER_ID1='userId1';
    CONST TABLE_CONNECTION_ATT_USER_ID2='userId2';
    CONST TABLE_CONNECTION_ATT_STATUS='status';
    
    CONST TABLE_FOLLOWER='tbl_follower';
    CONST TABLE_FOLLOWER_ATT_FOLLOW_ID='followId';
    CONST TABLE_FOLLOWER_ATT_USER_ID='userId';
    CONST TABLE_FOLLOWER_ATT_FOLLOWER_ID='followerId';
    
    CONST TABLE_LIKE='tbl_like';
    CONST TABLE_LIKE_ATT_ID='id';
    CONST TABLE_LIKE_ATT_USER_ID='userId';
    CONST TABLE_LIKE_ATT_FEED_ID='feedId';
    CONST TABLE_LIKE_ATT_LIKE_TYPE='likeType';
    
    CONST TABLE_COMMENT='tbl_comment';
    CONST TABLE_COMMENT_ATT_COMMENT_ID='commentId';
    CONST TABLE_COMMENT_ATT_USER_ID='userId';
    CONST TABLE_COMMENT_ATT_FEED_ID='feedId';
    CONST TABLE_COMMENT_ATT_COMMENT='comment';
    
    CONST TABLE_ADMIN = 'tbl_admin';
    CONST TABLE_ADMIN_ATT_ADMIN_ID = 'adminId';
    CONST TABLE_ADMIN_ATT_ADMIN_USERNAME = 'adminUsername';
    CONST TABLE_ADMIN_ATT_ADMIN_PASSWORD = 'adminPassword';
    CONST TABLE_ADMIN_ATT_ADMIN_LAST_LOGIN_TIME = 'adminLastLoginTime';
    CONST TABLE_ADMIN_ATT_ADMIN_IS_ACTIVE = 'adminIsActive';
    CONST TABLE_ADMIN_ATT_ADMIN_PREVILEDGE = 'adminPreviledge';
    
    CONST TABLE_CONTENT = 'tbl_content';
    CONST TABLE_CONTENT_ATT_CONTENT_ID = 'contentId';
    CONST TABLE_CONTENT_ATT_CONTENT_NAME = 'contentName';
    CONST TABLE_CONTENT_ATT_CONTENT_TITLE = 'contentTitle';
    CONST TABLE_CONTENT_ATT_CONTENT_DETAILS = 'contentDetails';
    
    CONST TABLE_SETTINGS = 'tbl_settings';
    CONST TABLE_SETTINGS_ATT_ID = 'id';
    CONST TABLE_SETTINGS_ATT_SITE_TITLE = 'siteTitle';
    CONST TABLE_SETTINGS_ATT_SITE_META_KEYWORD = 'siteMetaKeyword';
    CONST TABLE_SETTINGS_ATT_SITE_META_DESCRIPTION = 'siteMetaDescription';
    CONST TABLE_SETTINGS_ATT_SITE_LOGO = 'siteLogo';
    CONST TABLE_SETTINGS_ATT_SITE_EMAIL = 'siteEmail';
    CONST TABLE_SETTINGS_ATT_SITE_PHONE = 'sitePhone';
    CONST TABLE_SETTINGS_ATT_SITE_VENDOR_LOGO = 'siteVendorLogo';
    CONST TABLE_SETTINGS_ATT_SITE_DISPLAY_ADS_NO = 'siteDisplayAdsNo';
    
    CONST TABLE_ADS = 'tbl_ads';
    CONST TABLE_ADS_ATT_AD_ID = 'adId';
    CONST TABLE_ADS_ATT_AD_FILE_NAME = 'adFileName';
    CONST TABLE_ADS_ATT_AD_SCRIPT = 'adScript';
    CONST TABLE_ADS_ATT_AD_LINK = 'adLink';
    CONST TABLE_ADS_ATT_AD_IS_ACTIVE = 'adIsActive';
    CONST TABLE_ADS_ATT_AD_TYPE = 'adType';
    CONST TABLE_ADS_ATT_ADDED_DATE = 'addedDate';
    
    CONST TABLE_REPORTED_POSTS = 'tbl_reported_posts';
    CONST TABLE_REPORTED_POSTS_ATT_ID = 'id';
    CONST TABLE_REPORTED_POSTS_ATT_FEED_ID = 'feedId';
    CONST TABLE_REPORTED_POSTS_ATT_REPORTED_BY = 'reportBy';
    CONST TABLE_REPORTED_POSTS_ATT_REPORT_REASON = 'reportReason';
    CONST TABLE_REPORTED_POSTS_ATT_TIME = 'time';
    
    CONST TABLE_REPORTED_USERS = 'tbl_reported_users';
    CONST TABLE_REPORTED_USERS_ATT_ID = 'id';
    CONST TABLE_REPORTED_USERS_ATT_USER_ID = 'userId';
    CONST TABLE_REPORTED_USERS_ATT_REPORTED_BY = 'reportBy';
    CONST TABLE_REPORTED_USERS_ATT_REPORT_REASON = 'reportReason';
    CONST TABLE_REPORTED_USERS_ATT_TIME = 'time';
    
    
    CONST TABLE_CHAT_MESSAGE = 'tbl_chat_message';
    CONST TABLE_CHAT_MESSAGE_ATT_CHAT_ID = 'chatId';
    CONST TABLE_CHAT_MESSAGE_ATT_FEED_ID = 'profileId';
    CONST TABLE_CHAT_MESSAGE_ATT_SENDER_ID = 'senderId';
    CONST TABLE_CHAT_MESSAGE_ATT_CHAT_MESSAGE = 'chatMessage';
    CONST TABLE_CHAT_MESSAGE_ATT_RECEIVER_ID = 'receiverId';
    CONST TABLE_CHAT_MESSAGE_ATT_TIME = 'time';
    CONST TABLE_CHAT_MESSAGE_ATT_IS_READ = 'isRead';
    
    CONST TABLE_ACCOUNT_DEACTIVATE_REASON = 'tbl_account_deactivate_reason';
    CONST TABLE_ACCOUNT_DEACTIVATE_REASON_ATT_ID = 'id';
    CONST TABLE_ACCOUNT_DEACTIVATE_REASON_ATT_REASON = 'reason';
    
    CONST TABLE_DELETED_ACCOUNT = 'tbl_deleted_account';
    CONST TABLE_DELETED_ACCOUNT_ATT_ID = 'id';
    CONST TABLE_DELETED_ACCOUNT_ATT_USER_ID = 'userId';
    CONST TABLE_DELETED_ACCOUNT_ATT_DELETE_REASON_ID = 'deleteReasonId';
    CONST TABLE_DELETED_ACCOUNT_ATT_EXPLANTION = 'explantion';
    CONST TABLE_DELETED_ACCOUNT_ATT_TIME = 'time';
    CONST TABLE_DELETED_ACCOUNT_ATT_IS_RETURN = 'isReturn';
    CONST TABLE_DELETED_ACCOUNT_ATT_RETURN_TIME = 'returnTime';
    
}
